[package]
name = "helios-dash"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
brush-parser = { version = "0.3.0", default-features = false }
futures = { version = "0.3.31", default-features = false, features = ["alloc", "std"] }
helios-api = { path = "../../api", default-features = false, features = ["fs", "io", "programs"] }

[lib]
name = "helios_dash"
path = "src/main.rs"
crate-type = ["cdylib"]
