[package]
name = "helios-aarch64"
version = "0.1.0"
edition.workspace = true

[features]
default = ["embedded-debugger"]
embedded-debugger = ["helios-kernel/embedded-debugger"]

[dependencies]
arm-gic = "0.9.0"
bytes = { version = "1.10.1", default-features = false }
critical-section = { version = "1.2.0", features = ["restore-state-usize"] }
fdt = { version = "0.1.5", default-features = false }
helios-hal.workspace = true
helios-kernel = { workspace = true, default-features = false, features = ["wasmtime-aarch64"] }
helios-virtio.workspace = true
limine = "0.6.3"
rand_chacha = { version = "0.3.1", default-features = false }
rand_core = { version = "0.6.4", default-features = false }
spin = "0.10.0"
triomphe = { version = "0.1.15", default-features = false }
tracing.workspace = true
