[workspace]
members = [
    "api", "api-macro", "hal", "hosted", "kernel", "kernel-macro", "programs/curl", "programs/debugger", "programs/init", "programs/ping", "programs/sh", "riscv", "shell", "shell-core", "shell-protocol", "virtio",
]
resolver = "2"


[package]
name = "helios"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
helios-hal = { path = "hal" }
helios-api = { path = "api" }
helios-hosted = { path = "hosted" }
helios-kernel-macro = { path = "kernel-macro" }
helios-shell-protocol = { path = "shell-protocol" }
helios-riscv = { path = "riscv" }
helios-kernel = { path = "kernel" }
helios = { path = "." }
tracing = { version = "0.1.44",  default-features = false }
wit-bindgen = { version = "0.53.0", default-features = false }


[target.'cfg(not(target_os = "none"))'.dependencies]
helios-hosted.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
helios-riscv.workspace = true

[dev-dependencies]
helios-shell-protocol.workspace = true
wasmtime = { path = "../wasmtime/crates/wasmtime", default-features = false, features = ["component-model", "cranelift", "runtime", "std"] }

[profile.dev]
panic = "abort"

[profile.dev.package."*"]
opt-level = 2
debug = 0
debug-assertions = false
overflow-checks = false

[profile.dev.package.helios-debugger]
debug = 0
opt-level = "z"

[profile.dev.package.helios-ping]
debug = 0
opt-level = "z"
codegen-units = 1

[profile.dev.package.helios-curl]
debug = 0
opt-level = "z"
codegen-units = 1

[profile.dev.package.helios-api]
debug = 0
opt-level = "z"

[profile.dev.package.helios-shell-protocol]
debug = 0
opt-level = "z"

[profile.release]
panic = "abort"
