[workspace]
members = [
    "aarch64", "api", "api-macro", "artifact", "cli", "compiler-abi", "compiler-plugin", "compiler-support", "hal", "i6300esb", "hosted", "kernel", "kernel-macro", "programs/debugger", "programs/init", "programs/sh", "riscv", "x86", "inspector", "inspector-protocol", "virtio",
]
resolver = "2"


[package]
name = "helios"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
helios-hal = { path = "hal" }
helios-api = { path = "api" }
helios-artifact = { path = "artifact" }
helios-compiler-abi = { path = "compiler-abi" }
helios-compiler-support = { path = "compiler-support" }
helios-hosted = { path = "hosted" }
helios-aarch64 = { path = "aarch64" }
helios-kernel-macro = { path = "kernel-macro" }
helios-inspector-protocol = { path = "inspector-protocol" }
helios-riscv = { path = "riscv" }
helios-kernel = { path = "kernel", default-features = false }
helios-x86 = { path = "x86" }
i6300esb = { path = "i6300esb" }
helios = { path = "." }
tracing = { version = "0.1.44",  default-features = false }
wit-bindgen = { version = "0.53.0", default-features = false }


[target.'cfg(not(target_os = "none"))'.dependencies]
helios-hosted.workspace = true

[target.'cfg(target_arch = "riscv64")'.dependencies]
helios-riscv.workspace = true

[target.'cfg(target_arch = "aarch64")'.dependencies]
helios-aarch64.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
helios-x86.workspace = true

[dev-dependencies]
helios-inspector-protocol.workspace = true
wasmtime = { path = "../wasmtime/crates/wasmtime", default-features = false, features = ["component-model", "cranelift", "gc-null", "runtime", "std"] }

[profile.dev]
panic = "abort"
debug = 0
strip = "symbols"

[profile.dev.package."*"]
opt-level = 2
debug = 0
debug-assertions = false
overflow-checks = false

[profile.dev.package.helios-debugger]
debug = 0
opt-level = "z"

[profile.dev.package.helios-api]
debug = 0
opt-level = "z"

[profile.dev.package.helios-inspector-protocol]
debug = 0
opt-level = "z"

[profile.kernel-debug]
inherits = "dev"
debug = 2
strip = "none"

[profile.kernel-debug.package."*"]
opt-level = 2
debug = 1
debug-assertions = false
overflow-checks = false

[profile.kernel-debug.package.helios]
debug = 2

[profile.kernel-debug.package.helios-kernel]
debug = 2

[profile.kernel-debug.package.helios-riscv]
debug = 2

[profile.kernel-debug.package.helios-x86]
debug = 2

[profile.release]
panic = "abort"
