[package]
name = "helios-netstack"
version = "0.1.0"
edition.workspace = true

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bytes = { version = "1.10.1", default-features = false }
helios-hal.workspace = true
heapless = { version = "0.7.17", default-features = false }
thiserror = { version = "2.0.17", default-features = false }
wide = { version = "1.3.0", default-features = false }

[dev-dependencies]
divan = { version = "0.1.21", default-features = false }

[[bench]]
name = "hot_paths"
harness = false
