[package]
name = "helios-compiler-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
cranelift-codegen = { path = "../../wasmtime/cranelift/codegen", features = ["host-arch", "timing"] }
helios-compiler-abi.workspace = true
helios-compiler-support.workspace = true
log = { version = "0.4.29", features = ["std"] }
