[package]
name = "helios-compiler-plugin"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
cranelift-codegen = { path = "../../wasmtime/cranelift/codegen", features = ["host-arch", "timing"] }
helios-compiler-abi.workspace = true
helios-compiler-support.workspace = true
tracing.workspace = true
tracing-log = { version = "0.2.0", default-features = false, features = ["log-tracer", "std"] }
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["fmt", "std"] }

[lints]
workspace = true
