[package]
name = "helios-kernel"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
async-lock = { version = "3.4.2", default-features = false }
async-task = { version = "4.7.1", default-features = false }
atomic-waker = "1.1.2"
buddy_system_allocator = "0.12.0"
concurrent-queue = { version = "2.5.0", default-features = false }
critical-section = "1.2.0"
event-listener = { version = "5.4.1", default-features = false, features = ["critical-section"] }
nu-ansi-term = { version = "0.50.3", default-features = false }
objectpool = { version = "0.1.0", default-features = false, features = ["alloc"] }
helios-hal.workspace = true
thiserror = { version = "2.0.17", default-features = false }
tracing.workspace = true
bitflags = "2.11.0"
lru = { version = "0.16.3", default-features = false, features = ["hashbrown"] }
spin = { version = "0.9.8", default-features = false, features = ["mutex", "spin_mutex"] }

[dev-dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
futures-lite = "2.6.1"
helios-kernel-macro.workspace = true
wasm-encoder = "0.245.0"

[build-dependencies]
toml = "0.8.23"
walkdir = "2.5.0"
wit-component = "0.245.0"
wasmparser = "0.245.0"

[target.'cfg(all(target_os = "none", target_arch = "riscv64"))'.dependencies]
wasmtime = { path = "../../wasmtime/crates/wasmtime", default-features = false, features = ["call-hook", "component-model", "component-model-async", "riscv64", "cranelift", "runtime"] }
wasmtime-wasi-io = { path = "../../wasmtime/crates/wasi-io", default-features = false }

[target.'cfg(all(target_os = "none", target_arch = "x86_64"))'.dependencies]
wasmtime = { path = "../../wasmtime/crates/wasmtime", default-features = false, features = ["call-hook", "component-model", "component-model-async", "x86", "cranelift", "runtime"] }
wasmtime-wasi-io = { path = "../../wasmtime/crates/wasi-io", default-features = false }

[target.'cfg(not(target_os = "none"))'.dependencies]
wasmtime = { path = "../../wasmtime/crates/wasmtime", default-features = false, features = ["call-hook", "component-model", "component-model-async", "host-arch", "cranelift", "runtime", "std"] }
wasmtime-wasi-io = { path = "../../wasmtime/crates/wasi-io" }
