[package]
name = "helios-debugger"
version = "0.1.0"
edition.workspace = true
autobins = false

[dependencies]
futures-io = "0.3.31"
helios-api = { path = "../../api", default-features = false, features = ["instances", "profiling", "programs", "serial", "stats", "tracing", "vsock"] }
helios-inspector-protocol = { path = "../../inspector-protocol", default-features = false, features = ["guest"] }
thiserror = "2.0.17"

[lib]
name = "helios_debugger"
path = "src/main.rs"
crate-type = ["cdylib"]

[lints]
workspace = true
