#![no_std]

extern crate alloc;

use core::future::Future;

use helios_hal::io::IoResult;
use thiserror::Error;

/// Maximum Ethernet frame payload including the Ethernet header and FCS-free
/// frame bytes used by virtio-net and common Ethernet NICs.
pub const ETHERNET_FRAME_BYTES: usize = 1514;
/// Conservative default poll budget for single-queue virtio-style devices.
pub const DEFAULT_POLL_BUDGET: usize = 8;

/// Ethernet MAC address carried by the network interface boundary.
pub type EthernetAddress = [u8; 6];

/// Hardware checksum offload capabilities exposed by a NIC.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ChecksumOffload {
    /// IPv4 header checksum can be validated by hardware on receive.
    pub rx_ipv4: bool,
    /// TCP checksum can be validated by hardware on receive.
    pub rx_tcp: bool,
    /// UDP checksum can be validated by hardware on receive.
    pub rx_udp: bool,
    /// IPv4 header checksum can be generated by hardware on transmit.
    pub tx_ipv4: bool,
    /// TCP checksum can be generated by hardware on transmit.
    pub tx_tcp: bool,
    /// UDP checksum can be generated by hardware on transmit.
    pub tx_udp: bool,
}

/// Hardware segmentation and coalescing capabilities.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct SegmentationOffload {
    /// TCP segmentation offload for IPv4 packets.
    pub tx_tcp_ipv4: bool,
    /// TCP large receive offload for IPv4 packets.
    pub rx_tcp_ipv4: bool,
    /// Maximum payload bytes accepted by TSO.
    pub max_tx_segment_bytes: usize,
}

/// Multi-queue and flow steering capabilities.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct QueueTopology {
    /// Number of receive queues available to the stack.
    pub rx_queues: usize,
    /// Number of transmit queues available to the stack.
    pub tx_queues: usize,
    /// Receive-side scaling hash can steer flows across receive queues.
    pub rss: bool,
}

/// Event delivery and moderation capabilities for avoiding interrupt storms.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EventDeliveryCapabilities {
    /// Device progress can be polled without waiting for an interrupt.
    pub polling: bool,
    /// Device can notify progress through interrupts.
    pub interrupts: bool,
    /// Device or driver can adapt interrupt moderation to load.
    pub adaptive_moderation: bool,
    /// Receive interrupts can be coalesced.
    pub rx_coalescing: bool,
    /// Transmit-completion interrupts can be coalesced.
    pub tx_coalescing: bool,
    /// Preferred maximum receive frames to drain before yielding.
    pub rx_poll_budget: usize,
    /// Preferred maximum transmit completions to drain before yielding.
    pub tx_completion_budget: usize,
}

/// Hardware capabilities that let the stack specialize hot paths.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InterfaceCapabilities {
    /// Maximum FCS-free frame bytes the interface accepts.
    pub max_frame_len: usize,
    /// Supported checksum offloads.
    pub checksum: ChecksumOffload,
    /// Supported segmentation and coalescing offloads.
    pub segmentation: SegmentationOffload,
    /// Queue topology visible to the stack.
    pub queues: QueueTopology,
    /// Event delivery and moderation capabilities.
    pub events: EventDeliveryCapabilities,
    /// DMA can read borrowed packet bytes directly when that path wins.
    pub direct_tx_dma: bool,
    /// DMA can fill stack-owned packet buffers directly when that path wins.
    pub direct_rx_dma: bool,
}

/// Caller-owned packet storage used at stack/NIC boundaries.
///
/// This type is intentionally fixed-capacity. Stack code may pool it, pass it
/// between per-core queues, or lend it to NIC rings without growing heap state
/// on the hot path.
#[derive(Clone)]
pub struct PacketBuffer {
    bytes: [u8; ETHERNET_FRAME_BYTES],
    len: usize,
}

impl PacketBuffer {
    /// Creates an empty packet buffer.
    pub const fn new() -> Self {
        Self {
            bytes: [0; ETHERNET_FRAME_BYTES],
            len: 0,
        }
    }

    /// Returns the initialized frame bytes.
    pub fn as_slice(&self) -> &[u8] {
        &self.bytes[..self.len]
    }

    /// Returns writable frame capacity for a NIC or protocol encoder.
    pub fn spare_capacity_mut(&mut self) -> &mut [u8] {
        &mut self.bytes[self.len..]
    }

    /// Sets the initialized byte length after a caller has filled the buffer.
    pub fn set_len(&mut self, len: usize) {
        assert!(
            len <= self.bytes.len(),
            "packet buffer length exceeds Ethernet frame capacity"
        );
        self.len = len;
    }

    /// Clears initialized length without modifying storage.
    pub fn clear(&mut self) {
        self.len = 0;
    }
}

impl Default for PacketBuffer {
    fn default() -> Self {
        Self::new()
    }
}

/// Multi-core aware network interface contract used by packet stacks.
///
/// The interface is intentionally packet-oriented: device drivers expose
/// RX/TX frame movement and progress notification, while TCP/UDP policy lives
/// behind a replaceable stack implementation. The API permits direct DMA and
/// copy-based paths; the stack selects whichever path produces better measured
/// throughput for the packet size, queue topology, and hardware offloads.
pub trait NetworkInterface: Clone + Send + Sync + 'static {
    /// Returns the hardware MAC address programmed for this interface.
    fn mac_address(&self) -> EthernetAddress;

    /// Returns the largest Ethernet frame the interface accepts.
    fn max_frame_len(&self) -> usize;

    /// Returns hardware capabilities used to select stack data paths.
    fn capabilities(&self) -> InterfaceCapabilities {
        InterfaceCapabilities {
            max_frame_len: self.max_frame_len(),
            ..InterfaceCapabilities::default()
        }
    }

    /// Attempts to receive one frame into caller-owned storage.
    fn try_receive<'a>(
        &'a self,
        buffer: &'a mut PacketBuffer,
    ) -> impl Future<Output = IoResult<bool>> + Send + 'a;

    /// Transmits one borrowed frame and waits until the device accepts ownership.
    fn transmit<'a>(&'a self, frame: &'a [u8]) -> impl Future<Output = IoResult<()>> + Send + 'a;

    /// Waits for interface progress, such as RX arrival or TX completion.
    fn wait_for_event(&self) -> impl Future<Output = ()> + Send + '_;
}

/// Batch-oriented optional fast path for interfaces with queue-level access.
pub trait NetworkInterfaceBatch: NetworkInterface {
    /// Receives into caller-owned packet buffers without allocating.
    fn receive_batch<'a>(
        &'a self,
        frames: &'a mut [PacketBuffer],
    ) -> impl Future<Output = IoResult<usize>> + Send + 'a {
        async move {
            let mut received = 0;
            for frame in frames {
                frame.clear();
                if !self.try_receive(frame).await? {
                    break;
                }
                received += 1;
            }
            Ok(received)
        }
    }

    /// Transmits borrowed frame slices in order.
    fn transmit_batch<'a>(
        &'a self,
        frames: &'a [&'a [u8]],
    ) -> impl Future<Output = IoResult<()>> + Send + 'a {
        async move {
            for frame in frames {
                self.transmit(frame).await?;
            }
            Ok(())
        }
    }
}

/// A stack implementation that owns protocol state above a network interface.
pub trait PacketStack<Interface>: Clone + Send + Sync + 'static
where
    Interface: NetworkInterface,
{
    /// Drives inbound and outbound packet progress for this stack.
    fn drive<'a>(
        &'a self,
        interface: &'a Interface,
    ) -> impl Future<Output = Result<StackProgress, StackError>> + Send + 'a;

    /// Waits until stack or device progress can be made.
    fn wait_for_progress<'a>(
        &'a self,
        interface: &'a Interface,
    ) -> impl Future<Output = ()> + Send + 'a;
}

/// Progress counters returned by a packet-stack drive cycle.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct StackProgress {
    /// Frames consumed from the network interface.
    pub received_frames: usize,
    /// Frames submitted to the network interface.
    pub transmitted_frames: usize,
}

impl StackProgress {
    /// Returns whether the drive cycle moved at least one frame.
    pub const fn made_progress(self) -> bool {
        self.received_frames != 0 || self.transmitted_frames != 0
    }
}

/// Packet-stack errors that are independent of any concrete TCP engine.
#[derive(Clone, Copy, Debug, Error, PartialEq, Eq)]
pub enum StackError {
    /// The backing network interface failed.
    #[error("network interface I/O failed")]
    Interface,
    /// Protocol state was internally inconsistent.
    #[error("network stack state is inconsistent")]
    InconsistentState,
}
