#![no_std]

extern crate alloc;

mod checksum;
mod congestion;
mod dhcp;
mod dns;
mod packet;
mod stack;
mod tcp;
mod types;

use core::future::Future;

use bytes::Bytes;
use helios_hal::io::IoResult;
use thiserror::Error;

pub use checksum::{
    icmpv6_checksum, icmpv6_checksum_valid, internet_checksum, ipv4_checksum, tcp_checksum_valid,
    tcp_pseudo_header_checksum, tcpv4_checksum, tcpv6_checksum, udp_checksum, udp_checksum_valid,
    udp_pseudo_header_checksum,
};
pub use congestion::{
    AckSample, BbrV3, CongestionControl, CongestionEvent, CongestionWindow, Cubic, NewReno,
    PacingRate, RecoveryAction,
};
pub use dhcp::{
    DHCP_CLIENT_PORT, DHCP_SERVER_PORT, DhcpClientMessage, DhcpDnsServers, DhcpMessageType,
    DhcpOptionBuffer, DhcpOptionWriter, DhcpPacket, DhcpServerMessage, MAX_DHCP_DNS_SERVERS,
};
pub use dns::{DNS_PORT, DnsMessage, DnsQuestionWriter, DnsResponse};
pub use packet::{
    ArpOperation, ArpPacket, EthernetFrame, EthernetProtocol, Icmpv4DestinationUnreachableCode,
    Icmpv4Echo, Icmpv4Packet, Icmpv6DestinationUnreachableCode, Icmpv6Echo, Icmpv6Packet,
    Icmpv6PacketTooBig, IpProtocol, Ipv4Packet, Ipv6Packet, MAX_TCP_SACK_BLOCKS, TcpFlags,
    TcpHeader, TcpHeaderOptions, TcpOptions, TcpPacket, TcpSackBlock, TcpSackBlocks,
    TcpTimestampOption, TransportChecksum, TransportPorts, UdpPacket,
};
pub use stack::{
    DEFAULT_TCP_LISTEN_BACKLOG, DhcpLease, DnsQueryId, IcmpEchoKey, Ipv4MulticastMembership,
    MAX_IPV4_MULTICAST_MEMBERSHIPS, MAX_OUTBOUND_FRAMES, MAX_UDP_RX, MAX_UDP_SOCKETS,
    NeighborEntry, NeighborState, OutboundBatchStatus, Route, RouteTable, RxChecksumOffload,
    SocketId, Stack, StackConfig, StackEvent, StackInstant, TcpAccept, TcpConnectState,
    TcpConnectTerminalError, TcpListenBacklog, TcpReadIntoState, TcpReadState, UdpEndpoint,
    UdpPayload, UdpReceive, UdpSocketBinding, UdpSocketError, UdpSocketId,
};
pub use tcp::TCP_TRANSMIT_BUFFER_BYTES;
pub use tcp::{TcpEndpoint, TcpReset, TcpSegmentOutcome, TcpSocket, TcpState, TcpTransmitSegment};
pub use types::{
    EthernetAddress, IpAddress, IpCidr, Ipv4Address, Ipv4Cidr, Ipv6Address, Ipv6Cidr, Ipv6Scope,
};

/// Maximum Ethernet frame payload including the Ethernet header and FCS-free
/// frame bytes used by virtio-net and common Ethernet NICs.
pub const ETHERNET_FRAME_BYTES: usize = 1514;
/// Conservative default poll budget for single-queue virtio-style devices.
pub const DEFAULT_POLL_BUDGET: usize = 8;

/// Hardware checksum offload capabilities exposed by a NIC.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct ChecksumOffload {
    /// IPv4 header checksum can be validated by hardware on receive.
    pub rx_ipv4: bool,
    /// TCP checksum can be validated by hardware on receive.
    pub rx_tcp: bool,
    /// UDP checksum can be validated by hardware on receive.
    pub rx_udp: bool,
    /// IPv4 header checksum can be generated by hardware on transmit.
    pub tx_ipv4: bool,
    /// TCP checksum can be generated by hardware on transmit.
    pub tx_tcp: bool,
    /// UDP checksum can be generated by hardware on transmit.
    pub tx_udp: bool,
}

/// Hardware segmentation and coalescing capabilities.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct SegmentationOffload {
    /// TCP segmentation offload for IPv4 packets.
    pub tx_tcp_ipv4: bool,
    /// TCP large receive offload for IPv4 packets.
    pub rx_tcp_ipv4: bool,
    /// Maximum payload bytes accepted by TSO.
    pub max_tx_segment_bytes: usize,
}

/// Multi-queue and flow steering capabilities.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct QueueTopology {
    /// Number of receive queues available to the stack.
    pub rx_queues: usize,
    /// Number of transmit queues available to the stack.
    pub tx_queues: usize,
    /// Receive-side scaling hash can steer flows across receive queues.
    pub rss: bool,
}

/// Event delivery and moderation capabilities for avoiding interrupt storms.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EventDeliveryCapabilities {
    /// Device progress can be polled without waiting for an interrupt.
    pub polling: bool,
    /// Device can notify progress through interrupts.
    pub interrupts: bool,
    /// Device or driver can adapt interrupt moderation to load.
    pub adaptive_moderation: bool,
    /// Receive interrupts can be coalesced.
    pub rx_coalescing: bool,
    /// Transmit-completion interrupts can be coalesced.
    pub tx_coalescing: bool,
    /// Preferred maximum receive frames to drain before yielding.
    pub rx_poll_budget: usize,
    /// Preferred maximum transmit completions to drain before yielding.
    pub tx_completion_budget: usize,
}

/// Hardware capabilities that let the stack specialize hot paths.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InterfaceCapabilities {
    /// Maximum FCS-free frame bytes the interface accepts.
    pub max_frame_len: usize,
    /// Supported checksum offloads.
    pub checksum: ChecksumOffload,
    /// Supported segmentation and coalescing offloads.
    pub segmentation: SegmentationOffload,
    /// Queue topology visible to the stack.
    pub queues: QueueTopology,
    /// Event delivery and moderation capabilities.
    pub events: EventDeliveryCapabilities,
    /// DMA can read borrowed packet bytes directly when that path wins.
    pub direct_tx_dma: bool,
    /// DMA can fill stack-owned packet buffers directly when that path wins.
    pub direct_rx_dma: bool,
}

pub trait TcpReceiveBuffer {
    fn remaining_capacity(&self) -> usize;
    fn write_from(&mut self, bytes: &[u8]) -> usize;
}

/// Caller-owned packet storage used at stack/NIC boundaries.
#[derive(Clone, Debug)]
pub struct PacketBuffer {
    bytes: [u8; ETHERNET_FRAME_BYTES],
    len: usize,
    tx_checksum: Option<TxChecksum>,
}

/// Transmit checksum metadata for a frame whose transport checksum the
/// device finishes: the one's-complement sum continues from byte
/// `start` of the frame and the complemented result is stored at
/// `start + offset` (virtio 1.2 §5.1.6.2).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TxChecksum {
    pub start: u16,
    pub offset: u16,
}

/// Borrowed transmit frame plus its checksum-offload metadata, handed
/// to [`NetworkInterface`] slice transmit entry points.
#[derive(Clone, Copy, Debug)]
pub struct TxFrameRef<'a> {
    pub bytes: &'a [u8],
    pub checksum: Option<TxChecksum>,
}

impl PacketBuffer {
    /// Creates an empty packet buffer.
    pub const fn new() -> Self {
        Self {
            bytes: [0; ETHERNET_FRAME_BYTES],
            len: 0,
            tx_checksum: None,
        }
    }

    /// Checksum-offload metadata attached by the stack's encoders.
    pub const fn tx_checksum(&self) -> Option<TxChecksum> {
        self.tx_checksum
    }

    /// Attaches or clears checksum-offload metadata for this frame.
    pub fn set_tx_checksum(&mut self, checksum: Option<TxChecksum>) {
        self.tx_checksum = checksum;
    }

    /// Borrowed transmit view carrying the offload metadata.
    pub fn as_tx_frame(&self) -> TxFrameRef<'_> {
        TxFrameRef {
            bytes: self.as_slice(),
            checksum: self.tx_checksum,
        }
    }

    /// Returns the initialized frame bytes.
    pub fn as_slice(&self) -> &[u8] {
        &self.bytes[..self.len]
    }

    /// Returns mutable initialized frame bytes.
    pub fn as_mut_slice(&mut self) -> &mut [u8] {
        &mut self.bytes[..self.len]
    }

    /// Returns writable frame capacity for a NIC or protocol encoder.
    pub fn spare_capacity_mut(&mut self) -> &mut [u8] {
        &mut self.bytes[self.len..]
    }

    /// Returns full mutable frame storage for encoders that fill from offset zero.
    pub fn storage_mut(&mut self) -> &mut [u8; ETHERNET_FRAME_BYTES] {
        &mut self.bytes
    }

    /// Sets the initialized byte length after a caller has filled the buffer.
    pub fn set_len(&mut self, len: usize) {
        assert!(
            len <= self.bytes.len(),
            "packet buffer length exceeds Ethernet frame capacity"
        );
        self.len = len;
    }

    /// Clears initialized length and metadata without modifying storage.
    pub fn clear(&mut self) {
        self.len = 0;
        self.tx_checksum = None;
    }
}

impl AsRef<[u8]> for PacketBuffer {
    fn as_ref(&self) -> &[u8] {
        self.as_slice()
    }
}

impl Default for PacketBuffer {
    fn default() -> Self {
        Self::new()
    }
}

/// Multi-core aware network interface contract used by packet stacks.
pub trait NetworkInterface: Clone + Send + Sync + 'static {
    /// Returns the hardware MAC address programmed for this interface.
    fn mac_address(&self) -> EthernetAddress;

    /// Returns the largest Ethernet frame the interface accepts.
    fn max_frame_len(&self) -> usize;

    /// Returns the number of TX/RX queue pairs the device exposes.
    /// Single-queue devices return 1; virtio-net with
    /// `VIRTIO_NET_F_MQ` returns the negotiated pair count. The
    /// kernel network service uses this to size its per-CPU
    /// `NetworkShard` set and to dispatch TX submissions across
    /// queues so per-CPU sends do not contend on the same ring.
    fn queue_pair_count(&self) -> usize {
        1
    }

    /// Returns hardware capabilities used to select stack data paths.
    fn capabilities(&self) -> InterfaceCapabilities {
        InterfaceCapabilities {
            max_frame_len: self.max_frame_len(),
            ..InterfaceCapabilities::default()
        }
    }

    /// Attempts to receive one frame into caller-owned storage.
    fn try_receive<'a>(
        &'a self,
        buffer: &'a mut PacketBuffer,
    ) -> impl Future<Output = IoResult<bool>> + Send + 'a;

    /// Attempts to receive one frame as an owning device buffer.
    fn try_receive_frame(&self) -> impl Future<Output = IoResult<Option<Bytes>>> + Send;

    /// Attempts to receive owning device buffers without waiting for any async lock or event.
    fn try_receive_frames_immediate<'a, 'slots>(
        &'a self,
        frames: &'slots mut [Option<Bytes>],
    ) -> IoResult<Option<usize>>
    where
        'a: 'slots,
    {
        let _ = frames;
        Ok(None)
    }

    /// Variant of `try_receive_frames_immediate` that drains a specific
    /// RX queue pair so per-processor pollers do not contend on the
    /// other pairs. Defaults to the all-pairs path for single-queue
    /// devices.
    fn try_receive_frames_immediate_on<'a, 'slots>(
        &'a self,
        queue_idx: usize,
        frames: &'slots mut [Option<Bytes>],
    ) -> IoResult<Option<usize>>
    where
        'a: 'slots,
    {
        let _ = queue_idx;
        self.try_receive_frames_immediate(frames)
    }

    /// Releases an owning device RX frame back to the interface.
    fn repost_rx_frame<'a>(
        &'a self,
        frame: Bytes,
    ) -> impl Future<Output = IoResult<()>> + Send + 'a;

    /// Releases owning device RX frames without waiting for any async lock or event.
    fn repost_rx_frames_immediate<'a, 'slots>(
        &'a self,
        frames: &'slots mut [Option<Bytes>],
    ) -> IoResult<Option<()>>
    where
        'a: 'slots,
    {
        let _ = frames;
        Ok(None)
    }

    /// Transmits one borrowed frame and waits until the device accepts ownership.
    fn transmit<'a>(&'a self, frame: &'a [u8]) -> impl Future<Output = IoResult<()>> + Send + 'a;

    /// Transmits borrowed frame slices in order.
    fn transmit_batch<'a>(
        &'a self,
        frames: &'a [&'a [u8]],
    ) -> impl Future<Output = IoResult<()>> + Send + 'a {
        async move {
            for frame in frames {
                self.transmit(frame).await?;
            }
            Ok(())
        }
    }

    /// Transmits stack-owned packet buffers in order.
    fn transmit_packet_batch<'a>(
        &'a self,
        frames: &'a [PacketBuffer],
    ) -> impl Future<Output = IoResult<()>> + Send + 'a {
        async move {
            for frame in frames {
                self.transmit(frame.as_slice()).await?;
            }
            Ok(())
        }
    }

    /// Attempts to submit stack-owned packet buffers and returns the accepted frame count.
    fn try_transmit_packet_batch<'a>(
        &'a self,
        frames: &'a [PacketBuffer],
    ) -> impl Future<Output = IoResult<usize>> + Send + 'a {
        async move {
            if frames.is_empty() {
                return Ok(0);
            }
            self.transmit(frames[0].as_slice()).await?;
            Ok(1)
        }
    }

    /// Variant of `try_transmit_packet_batch` that submits to a
    /// specific TX queue pair. The default implementation routes
    /// every queue index to the single-queue path; multi-queue
    /// devices override this to dispatch directly to the requested
    /// queue without locking the other pairs' rings.
    fn try_transmit_packet_batch_on<'a>(
        &'a self,
        queue_idx: usize,
        frames: &'a [PacketBuffer],
    ) -> impl Future<Output = IoResult<usize>> + Send + 'a {
        let _ = queue_idx;
        self.try_transmit_packet_batch(frames)
    }

    /// Attempts to submit borrowed frames (with their checksum-offload
    /// metadata) without waiting for any async lock or event.
    fn try_transmit_slices_immediate(&self, frames: &[TxFrameRef<'_>]) -> IoResult<Option<usize>> {
        let _ = frames;
        Ok(None)
    }

    /// Variant of `try_transmit_slices_immediate` that submits to a
    /// specific TX queue pair. Same default-routes-to-queue-0
    /// pattern as the packet-batch counterpart above.
    fn try_transmit_slices_immediate_on(
        &self,
        queue_idx: usize,
        frames: &[TxFrameRef<'_>],
    ) -> IoResult<Option<usize>> {
        let _ = queue_idx;
        self.try_transmit_slices_immediate(frames)
    }

    /// Reclaims completed transmit slots without waiting for new device events.
    fn reclaim_transmit_completions(
        &self,
        budget: usize,
    ) -> impl Future<Output = IoResult<usize>> + Send + '_ {
        let _ = budget;
        async { Ok(0) }
    }

    /// Variant of `reclaim_transmit_completions` that targets a
    /// specific TX queue pair.
    fn reclaim_transmit_completions_on(
        &self,
        queue_idx: usize,
        budget: usize,
    ) -> impl Future<Output = IoResult<usize>> + Send + '_ {
        let _ = queue_idx;
        self.reclaim_transmit_completions(budget)
    }

    /// Reclaims completed transmit slots without constructing an async wait path.
    fn reclaim_transmit_completions_immediate(&self, budget: usize) -> IoResult<Option<usize>> {
        let _ = budget;
        Ok(None)
    }

    /// Variant of `reclaim_transmit_completions_immediate` that
    /// targets a specific TX queue pair.
    fn reclaim_transmit_completions_immediate_on(
        &self,
        queue_idx: usize,
        budget: usize,
    ) -> IoResult<Option<usize>> {
        let _ = queue_idx;
        self.reclaim_transmit_completions_immediate(budget)
    }

    /// Waits for interface progress, such as RX arrival or TX completion.
    fn wait_for_event(&self) -> impl Future<Output = ()> + Send + '_;
}

/// Batch-oriented optional fast path for interfaces with queue-level access.
pub trait NetworkInterfaceBatch: NetworkInterface {
    /// Receives into caller-owned packet buffers without allocating.
    fn receive_batch<'a>(
        &'a self,
        frames: &'a mut [PacketBuffer],
    ) -> impl Future<Output = IoResult<usize>> + Send + 'a {
        async move {
            let mut received = 0;
            for frame in frames {
                frame.clear();
                if !self.try_receive(frame).await? {
                    break;
                }
                received += 1;
            }
            Ok(received)
        }
    }
}

/// A stack implementation that owns protocol state above a network interface.
pub trait PacketStack<Interface>: Clone + Send + Sync + 'static
where
    Interface: NetworkInterface,
{
    /// Drives inbound and outbound packet progress for this stack.
    fn drive<'a>(
        &'a self,
        interface: &'a Interface,
    ) -> impl Future<Output = Result<StackProgress, StackError>> + Send + 'a;

    /// Waits until stack or device progress can be made.
    fn wait_for_progress<'a>(
        &'a self,
        interface: &'a Interface,
    ) -> impl Future<Output = ()> + Send + 'a;
}

/// Progress counters returned by a packet-stack drive cycle.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct StackProgress {
    /// Frames consumed from the network interface.
    pub received_frames: usize,
    /// Frames submitted to the network interface.
    pub transmitted_frames: usize,
}

impl StackProgress {
    /// Returns whether the drive cycle moved at least one frame.
    pub const fn made_progress(self) -> bool {
        self.received_frames != 0 || self.transmitted_frames != 0
    }
}

/// Packet-stack errors that are independent of any concrete TCP engine.
#[derive(Clone, Copy, Debug, Error, PartialEq, Eq)]
pub enum StackError {
    /// The backing network interface failed.
    #[error("network interface I/O failed")]
    Interface,
    /// Protocol state was internally inconsistent.
    #[error("network stack state is inconsistent")]
    InconsistentState,
    /// An incoming packet was malformed.
    #[error("malformed network packet")]
    MalformedPacket,
    /// Outbound packet storage was exhausted.
    #[error("network stack output queue is full")]
    OutputQueueFull,
    /// The stack accepted the current packet but RX should stop until consumers drain sockets.
    #[error("network receive path is backpressured")]
    ReceiveBackpressure,
    /// The requested socket is unknown.
    #[error("unknown network socket")]
    UnknownSocket,
    /// A socket address set overlaps an existing socket.
    #[error("network socket address is already in use")]
    AddressInUse,
    /// A listen backlog value cannot be represented by the stack.
    #[error("TCP listen backlog is invalid")]
    InvalidListenBacklog,
    /// No local address can route the requested destination.
    #[error("network destination is unroutable")]
    Unroutable,
    /// Socket local and remote address families are inconsistent.
    #[error("network socket address families do not match")]
    AddressFamilyMismatch,
    /// A connected socket attempted to send to a different remote endpoint.
    #[error("network socket remote endpoint does not match")]
    RemoteAddressMismatch,
    /// A datagram or segment cannot fit in one packet for the current path.
    #[error("network packet exceeds transmit capacity")]
    PacketTooLarge,
    /// The requested multicast group address is invalid for the operation.
    #[error("network multicast group address is invalid")]
    InvalidMulticastGroup,
    /// The requested multicast interface is unavailable.
    #[error("network multicast interface is unavailable")]
    MulticastInterfaceUnavailable,
    /// The requested multicast membership does not exist.
    #[error("network multicast membership does not exist")]
    MulticastMembershipNotFound,
    /// Multicast membership storage was exhausted.
    #[error("network multicast membership table is full")]
    MulticastMembershipTableFull,
}
