[package]
name = "helios-procbench"
version = "0.1.0"
edition.workspace = true
autobins = false

[dependencies]
helios-api = { path = "../../api", default-features = false, features = ["channel", "instances", "programs", "stats", "task"] }
helios-bench-metrics = { path = "../../tools/wasi-apps/bench-metrics" }
thiserror = { version = "2.0.17", default-features = false }

[lib]
name = "helios_procbench"
path = "src/main.rs"
crate-type = ["cdylib"]
