[package]
name = "helios-virtio"
version = "0.1.0"
edition = "2024"

[dependencies]
async-lock = { version = "3.4.2", default-features = false }
bitflags = "2.11.0"
event-listener = { version = "5.4.1", default-features = false, features = ["critical-section"] }
helios-hal.workspace = true
spin = { version = "0.9.8", default-features = false, features = ["mutex", "spin_mutex"] }

[dev-dependencies]
futures-lite = "2.6.1"
zerocopy = { version = "0.8.27", features = ["derive"] }
