[package]
name = "helios-x86"
version = "0.1.0"
edition = "2024"

[dependencies]
acpi = "6.1.1"
critical-section = { version = "1.2.0", features = ["restore-state-bool"] }
helios-hal.workspace = true
i6300esb.workspace = true
helios-kernel = { workspace = true, default-features = false, features = ["wasmtime-x86"] }
limine = "0.5.0"
pci_types = "0.10.1"
spin = { version = "0.9.8", default-features = false, features = ["once"] }
x86 = "0.52.0"
x86_64 = { version = "0.15.3", default-features = false, features = ["instructions"] }
