[package]
name = "helios-riscv"
version = "0.1.0"
edition.workspace = true

[features]
default = ["embedded-debugger"]
embedded-debugger = ["helios-kernel/embedded-debugger"]

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bytes = { version = "1.10.1", default-features = false }
concurrent-queue = { version = "2.5.0", default-features = false }
critical-section = { version = "1.2.0", features = ["restore-state-usize"] }
fdt = { version = "0.1.5", default-features = false }
futures = { version = "0.3.31", default-features = false, features = ["alloc"] }
ns16550a = "0.5.0"
pci_types = "0.10.1"
plic = "0.0.3"
riscv = "0.16.0"
riscv-rt = { version = "0.17.1", features = ["s-mode"] }
sbi-rt = { version = "0.0.3", features = ["legacy"]}
sbi-spec = { version = "0.0.7", default-features = false }
spin = { version = "0.9.8", default-features = false, features = ["mutex", "once", "spin_mutex"] }
trapframe = { version = "0.10.1", default-features = false }
helios-hal.workspace = true
i6300esb.workspace = true
helios-kernel = { workspace = true, default-features = false, features = ["wasmtime-riscv64"] }
helios-virtio = { path = "../virtio" }
tracing.workspace = true
