[package]
name = "helios-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.5.0"
futures-core = "0.3.31"
futures-io = "0.3.31"
futures-lite = "2.6.1"
helios-api-macro = { path = "../api-macro" }
serde = { version = "1.0.228", features = ["derive"] }
wit-bindgen = { workspace = true, features = ["async", "async-spawn", "macros", "realloc"] }
