[package]
name = "helios-hosted"
version = "0.1.0"
edition = "2024"

[dependencies]
critical-section = { version = "1.2.0", features = ["std"] }
crossbeam-channel = "0.5.15"
futures-lite = "2.6.1"
helios-hal.workspace = true
helios-kernel.workspace = true
mimalloc = "0.1.48"
shell-words = "1.1.0"
tempfile = "3.23.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["io-std", "io-util", "net", "rt", "sync", "time"] }
tracing.workspace = true
wasmtime = { path = "../../wasmtime/crates/wasmtime", default-features = false, features = ["async", "component-model", "component-model-async", "cranelift", "runtime", "std"] }
wasmtime-wasi = { path = "../../wasmtime/crates/wasi", default-features = false, features = ["p2", "p3"] }
